# Importação de Bibliotecas

In [72]:
import pandas as pd 
import numpy as np
from sklearn.ensemble import RandomForestClassifier

# Carregando os Dados

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

# Modelo de Treinamento

In [5]:
modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)

In [6]:
modelo

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

# Criação do Modelo

In [7]:
variaveis=['Sex_binario', 'Age']

In [8]:
train['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [9]:
def transformar_sexo(valor):
    if valor == 'female':
        return 1
    else:
        return 0
train['Sex_binario'] = train['Sex'].map(transformar_sexo)

In [10]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_binario  
0      0         A/5 21171   7.2500   NaN        S            0  
1      0          PC 17599  71.2833   C85        C            1  
2      0  STON/O2. 3101282   7.9250   NaN        S            1  
3      0            113803  53.1000  C123        S            1  
4      0            373450   8.0500   NaN        S            0

In [11]:
X = train[variaveis]
y= train['Survived']

In [12]:
X.head()

Sex_binario   Age
0            0  22.0
1            1  38.0
2            1  26.0
3            1  35.0
4            0  35.0

In [13]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [14]:
modelo.fit(X,y)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [15]:
X = X.fillna(-1)

In [16]:
modelo.fit(X,y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [17]:
test['Sex_binario'] = test['Sex'].map(transformar_sexo)

In [18]:
X_prev = test[variaveis]
X_prev = X_prev.fillna(-1)
X_prev.head()

Sex_binario   Age
0            0  34.5
1            1  47.0
2            0  62.0
3            0  27.0
4            1  22.0

In [19]:
p= modelo.predict(X_prev)

In [20]:
p

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [21]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Sex_binario  
0  34.5      0      0   330911   7.8292   NaN        Q            0  
1  47.0      1      0   363272   7.0000   NaN        S            1  
2  62.0      0      0   240276   9.6875   NaN        Q            0  
3  27.0      0      0   315154   8.6625   NaN        S            0  
4  22.0      1      1  3101298  12.2875   NaN        S            1

# Criar Submission

In [25]:
sub=pd.Series(p, index=test['PassengerId'], name='Survived')
sub.shape

(418,)

In [26]:
sub.to_csv("primeiro_modelo.csv", header = True)

In [27]:
!head -n10 primeiro_modelo.csv

PassengerId,Survived
892,0
893,1
894,0
895,1
896,1
897,0
898,1
899,0
900,1


# Treino

In [28]:
# imports
from sklearn.model_selection import train_test_split

In [30]:
X_falso = np.arange(10)
X_falso

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
train_test_split(X_falso)

[array([8, 6, 5, 0, 2, 4, 9]), array([7, 3, 1])]

In [34]:
# Controle de aleatoriedade do modelo
np.random.seed(0)  # ou random_state=0
train_test_split(X_falso, test_size=0.5)

[array([6, 7, 3, 0, 5]), array([2, 8, 4, 9, 1])]

# Validação

In [35]:
np.random.seed(0)
X_treino, X_valid, y_treino, y_valid = train_test_split(X,y, test_size=0.5)


In [36]:
X_treino.head()

Sex_binario   Age
213            0  30.0
586            0  47.0
499            0  24.0
821            0  27.0
246            1  25.0

In [37]:
X_treino.shape, X_valid.shape, y_treino.shape, y_valid.shape

((445, 2), (446, 2), (445,), (446,))

In [38]:
modelo.fit(X_treino, y_treino)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [39]:
p= modelo.predict(X_valid)

In [43]:
y_valid == p

495     True
648     True
278    False
31      True
255     True
       ...  
327     True
827     True
102     True
625     True
108     True
Name: Survived, Length: 446, dtype: bool

In [44]:
np.mean(y_valid== p)   # acurácia

0.7690582959641256

In [47]:
p= (X_valid['Sex_binario']==1).astype(np.int64)
np.mean(y_valid == p)

0.7825112107623319

# Validação cruzada

In [66]:
X_falso

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# import
from sklearn.model_selection import KFold


In [68]:
kf = KFold(3, shuffle=True, random_state=0)
for linhas_treino, linhas_valid in kf.split(X_falso):
    print("Treino:", linhas_treino)
    print("Valid:", linhas_valid)
    print()

Treino: [0 1 3 5 6 7]
Valid: [2 4 8 9]

Treino: [0 2 3 4 5 8 9]
Valid: [1 6 7]

Treino: [1 2 4 6 7 8 9]
Valid: [0 3 5]



In [71]:
kf = KFold(3, shuffle=True, random_state=0)
for linhas_treino, linhas_valid in kf.split(X):
    print("Treino:", linhas_treino.shape[0])
    print("Valid:", linhas_valid.shape[0])
    print()
    X_treino, X_valid = X.iloc[linhas_treino], X.iloc[linhas_valid]
    y_treino, y_valid = y.iloc[linhas_treino], X.iloc[linhas_valid]
    #print(X_treino.head())
    #print()

Treino: 594
Valid: 297

Treino: 594
Valid: 297

Treino: 594
Valid: 297



In [90]:
kf = KFold(10, shuffle=True, random_state=1)
resultados =[]
for linhas_treino, linhas_valid in kf.split(X):
    print("Treino:", linhas_treino.shape[0])
    print("Valid:", linhas_valid.shape[0])

    X_treino, X_valid = X.iloc[linhas_treino], X.iloc[linhas_valid]
    y_treino, y_valid = y.iloc[linhas_treino], y.iloc[linhas_valid]
    
    modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
    modelo.fit(X_treino,y_treino)
    
    p = modelo.predict(X_valid)
    
    acc = np.mean(y_valid == p)
    resultados.append(acc)
    print("Acc:",acc)
    print()
    #print(X_treino.head())
    #print()

Treino: 801
Valid: 90
Acc: 0.7333333333333333

Treino: 802
Valid: 89
Acc: 0.797752808988764

Treino: 802
Valid: 89
Acc: 0.7078651685393258

Treino: 802
Valid: 89
Acc: 0.7191011235955056

Treino: 802
Valid: 89
Acc: 0.797752808988764

Treino: 802
Valid: 89
Acc: 0.7865168539325843

Treino: 802
Valid: 89
Acc: 0.8089887640449438

Treino: 802
Valid: 89
Acc: 0.797752808988764

Treino: 802
Valid: 89
Acc: 0.8202247191011236

Treino: 802
Valid: 89
Acc: 0.7640449438202247



In [91]:
resultados

[0.7333333333333333,
 0.797752808988764,
 0.7078651685393258,
 0.7191011235955056,
 0.797752808988764,
 0.7865168539325843,
 0.8089887640449438,
 0.797752808988764,
 0.8202247191011236,
 0.7640449438202247]

In [92]:
np.mean(resultados)

0.7733333333333333

In [97]:
resultados =[]
for rep in range(10):
    print("Rep:", rep)
    kf = KFold(10, shuffle=True, random_state=rep)

for linhas_treino, linhas_valid in kf.split(X):
    print("Treino:", linhas_treino.shape[0])
    print("Valid:", linhas_valid.shape[0])

    X_treino, X_valid = X.iloc[linhas_treino], X.iloc[linhas_valid]
    y_treino, y_valid = y.iloc[linhas_treino], y.iloc[linhas_valid]
    
    modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
    modelo.fit(X_treino,y_treino)
    
    p = modelo.predict(X_valid)
    
    acc = np.mean(y_valid == p)
    resultados.append(acc)
    print("Acc:",acc)
    print()
    #print(X_treino.head())
    #print()

Rep: 0
Rep: 1
Rep: 2
Rep: 3
Rep: 4
Rep: 5
Rep: 6
Rep: 7
Rep: 8
Rep: 9
Treino: 801
Valid: 90
Acc: 0.7444444444444445

Treino: 802
Valid: 89
Acc: 0.7303370786516854

Treino: 802
Valid: 89
Acc: 0.7752808988764045

Treino: 802
Valid: 89
Acc: 0.7640449438202247

Treino: 802
Valid: 89
Acc: 0.7640449438202247

Treino: 802
Valid: 89
Acc: 0.7078651685393258

Treino: 802
Valid: 89
Acc: 0.7752808988764045

Treino: 802
Valid: 89
Acc: 0.8202247191011236

Treino: 802
Valid: 89
Acc: 0.8089887640449438

Treino: 802
Valid: 89
Acc: 0.7865168539325843



In [98]:
resultados

[0.7444444444444445,
 0.7303370786516854,
 0.7752808988764045,
 0.7640449438202247,
 0.7640449438202247,
 0.7078651685393258,
 0.7752808988764045,
 0.8202247191011236,
 0.8089887640449438,
 0.7865168539325843]

In [99]:
np.mean(resultados)

0.7677028714107366